export const API_BASE_URL = "http://localhost:5000"
export const API_URL = API_BASE_URL + "/api"
export const LOGIN_URL = API_URL + "/auth/login"
export const SIGNUP_URL = API_URL + "/auth/register"
export const CHAT_GROUP = "http://localhost:5000/api/chat/chat-group"
export const CHAT_GROUP_USERS = API_URL + "/chat/chat-group-users"
export const CHATS_URL = API_URL + "/chat" + "/chats"
